// Generated by IcedCoffeeScript 1.4.0c
(function() {
  var iced, __iced_deferrals, __iced_k, __iced_k_noop,
    __slice = [].slice,
    _this = this;

  iced = {
    Deferrals: (function() {

      function _Class(_arg) {
        this.continuation = _arg;
        this.count = 1;
        this.ret = null;
      }

      _Class.prototype._fulfill = function() {
        if (!--this.count) return this.continuation(this.ret);
      };

      _Class.prototype.defer = function(defer_params) {
        var _this = this;
        ++this.count;
        return function() {
          var inner_params, _ref;
          inner_params = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          if (defer_params != null) {
            if ((_ref = defer_params.assign_fn) != null) {
              _ref.apply(null, inner_params);
            }
          }
          return _this._fulfill();
        };
      };

      return _Class;

    })(),
    findDeferral: function() {
      return null;
    },
    trampoline: function(_fn) {
      return _fn();
    }
  };
  __iced_k = __iced_k_noop = function() {};

  $.fn.formify = function() {
    return this.click(function() {
      var data, form;
      data = $(this).data();
      if (data.confirm) if (!confirm(data.confirm)) return;
      form = $('<form>').attr('method', 'post').attr('action', this.href);
      return form.submit();
    });
  };

  (function(__iced_k) {
    __iced_deferrals = new iced.Deferrals(__iced_k, {
      filename: "jquery.ex.iced"
    });
    $(__iced_deferrals.defer({
      lineno: 9
    }));
    __iced_deferrals._fulfill();
  })(function() {
    return $('.formify').formify();
  });

}).call(this);
